# name: DevSecOps Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   devsecops-demo:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout Code
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       # Step 2: Set Up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.8

#       # Step 3: Install Dependencies
#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 4: Run SonarCloud Analysis (Code Quality + SAST)
#       - name: SonarCloud Scan
#         uses: sonarsource/sonarcloud-github-action@v2
#         with:
#           args: >
#             -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
#             -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
#             -Dsonar.host.url=https://sonarcloud.io
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#       # Step 5: Build Docker Image
#       - name: Build Docker Image
#         run: docker build -t devsecops-demo:latest .

#       # Step 6: Install OPA
#       - name: Install OPA
#         run: |
#           curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
#           chmod +x opa
#           sudo mv opa /usr/local/bin/

#       # Step 7: Validate Dockerfile with OPA (Best Practices)
#       - name: Validate Dockerfile
#         run: |
#           opa eval --input Dockerfile --data policy/ --format pretty \
#             "data.docker.policy.deny" > policy-evaluation.txt

#       # Step 8: Scan Docker Image with Trivy (Vulnerability Scan)
#       - name: Scan Docker Image with Trivy
#         run: docker run --rm aquasec/trivy image devsecops-demo:latest

#       # Step 9: Optimize Docker Image with Docker Slim
#       - name: Optimize Docker Image
#         run: docker-slim build --tag devsecops-demo-optimized:latest devsecops-demo:latest

#       # Step 10: Sign Optimized Docker Image with Cosign
#       - name: Sign Docker Image
#         env:
#           COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
#         run: |
#           echo "$COSIGN_KEY" > cosign.key
#           cosign sign --key cosign.key devsecops-demo-optimized:latest

#       # Step 11: Push Signed Docker Image to Container Registry
#       - name: Push Docker Image
#         run: docker tag devsecops-demo-optimized:latest <your-docker-repo>/devsecops-demo:latest && \
#              docker push <your-docker-repo>/devsecops-demo:latest

#       # Step 12: Verify Signed Docker Image (Final Validation)
#       - name: Verify Signed Docker Image
#         env:
#           COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
#         run: |
#           echo "$COSIGN_KEY" > cosign.key
#           cosign verify --key cosign.key <your-docker-repo>/devsecops-demo:latest

name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  devsecops-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker (latest version)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker --version

      - name: Start Docker Service
        run: sudo service docker start

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sidwar/devsecops-demo:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: docker push sidwar/devsecops-demo:${{ github.sha }}

  sonar_scan:
    runs-on: ubuntu-latest
    needs: devsecops-demo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/index.xml  # Coverage report
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  validate_dockerfile:
    runs-on: ubuntu-latest
    needs: sonar_scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Validate Dockerfile with OPA (Best Practices)
        run: |
          opa eval --input Dockerfile --data policy/ --format pretty \
            "data.docker.policy.deny" > policy-evaluation.txt
          cat policy-evaluation.txt

  vulnerability_scan:
    runs-on: ubuntu-latest
    needs: validate_dockerfile

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Scan Docker Image with Trivy and Save Report
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/trivy-cache:/root/.cache/ \
            aquasec/trivy image --scanners vuln \
            --format json \
            --output trivy-report.json \
            sidwar/devsecops-demo:${{ github.sha }}

      - name: Upload Trivy Vulnerability Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-vulnerability-report
          path: trivy-report.json

  optimize_image:
    name: Optimize Docker Image
    runs-on: ubuntu-latest
    needs: vulnerability_scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull sidwar/devsecops-demo:${{ github.sha }}

      - name: Optimize Docker Image with Docker Slim
        uses: docker-slim/docker-slim-action@v5
        with:
          target: sidwar/devsecops-demo:${{ github.sha }}
          tag: sidwar/devsecops-demo:slim-${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Slimmed Docker Image
        run: docker push sidwar/devsecops-demo:slim-${{ github.sha }}

  sign_image:
    name: Sign Docker Image
    runs-on: ubuntu-latest
    needs: optimize_image

    steps:
      - name: Log in to Cosign
        run: |
          echo "$COSIGN_KEY" > cosign.key
          cosign sign --key cosign.key sidwar/devsecops-demo:slim-${{ github.sha }}

  verify_image:
    name: Verify Docker Image
    runs-on: ubuntu-latest
    needs: sign_image

    steps:
      - name: Verify Signed Docker Image
        run: |
          echo "$COSIGN_KEY" > cosign.key
          cosign verify --key cosign.key sidwar/devsecops-demo:slim-${{ github.sha }}
